export const TRANSITION_DURATION_MS = 500
export const SHADOW_MAP_RESOLUTION_HIGH = 2048
export const SHADOW_MAP_RESOLUTION_LOW = 512
export const BLOOM_INTENSITY = 0.3
export const BLOOM_LUMINANCE_THRESHOLD = 0.9
export const GPU_TIER_THRESHOLD = 2
